spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/bytebank_db
    username: bytebank
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
